### ISSUE TITLE
Issue when run FLASK

### ISSUE THREAD

**Issue by jamesc99** [lidaof/targetFileAPI#1]
Hey Daofeng,

I am trying to run qATACviewer to visualize the QC output of AIAP and I encountered some problem. When I run the FLASK, it shows 'Debugger is active!' and there is no output here for a long time. Do you have any advice about it?

Thanks,
Ryan

<img width="416" alt="Picture1" src="https://user-images.githubusercontent.com/81212185/145646786-f40f287e-ab0b-4351-aa3b-5bd43263ce90.png">

**Comment by lidaof** [comment]
Hi Ryan, thanks for using the tool.
This looks ok to me indicate the backend is running, would you be able to run the front end and get data?
